Preparation for 1.5.0-RC2 release.
- sbt-scalajs plugin version upgraded from 0.6.12 to 0.6.13 in "scalajs" scripted test.

BTW test failes without this change (https://travis-ci.org/scoverage/sbt-scoverage/builds/169005149) with exception:

org.scalajs.core.ir.IRVersionNotSupportedException: Failed to deserialize info of file compiled with Scala.js 0.6.13 (supported: 0.6.0, 0.6.3, 0.6.4, 0.6.6, 0.6.8, 0.6.5): /home/travis/.ivy2/cache/org.scoverage/scalac-scoverage-runtime_sjs0.6_2.11/jars/scalac-scoverage-runtime_sjs0.6_2.11-1.3.0-RC2.jar:scalajssupport/JsFileObject$class.sjsir